---
title: 'Chapter 3: Reliability'
author: "BRT"
date: "8/10/2020"
output: 
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: yes
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(fs)
theme_set(theme_minimal(base_size = 15) +
            theme(plot.title.position = "plot",
                  legend.position = "bottom"))
```

```{r load-data}
p <- here::here("data", "person-estimates") %>% 
  dir_ls() %>% 
  map_df(read_csv, .id = "f") %>% 
  mutate(f = gsub(here::here("data", "person-estimates"), "", f),
         grade = as.numeric(gsub("^/g(\\d\\d?).+", "\\1", f)),
         tier = as.numeric(gsub(".+\\dt(\\d).+", "\\1", f)),
         content = gsub(".+-(.+)\\..+", "\\1", f)) %>% 
  select(-f) 

i <- here::here("data", "item-estimates") %>% 
  dir_ls() %>% 
  map_df(read_csv, .id = "f") %>% 
  mutate(f = gsub(here::here("data", "item-estimates"), "", f),
         grade = as.numeric(gsub("^/g(\\d\\d?).+", "\\1", f)),
         tier = as.numeric(gsub(".+\\dt(\\d).+", "\\1", f)),
         content = gsub(".+-(.+)\\..+", "\\1", f)) %>% 
  select(-f)

items_by_test <- i %>% 
  group_by(grade, tier, content) %>% 
  nest()

persons_by_test <- p %>% 
  group_by(grade, tier, content) %>% 
  nest()
```

## Marginal Reliability
```{r marg-rel}
marg_rel <- function(theta, se) {
  s <- var(theta, na.rm = TRUE)
  e <- mean((se)^2, na.rm = TRUE)
  s/(s+e)
}
mr <- persons_by_test %>% 
  mutate(`Marginal Reliability` = map_dbl(data, ~marg_rel(.x$Theta, .x$SE))) %>% 
  select(-data) %>% 
  arrange(grade, tier, content)

names(mr)[1:3] <- stringr::str_to_title(names(mr)[1:3])
knitr::kable(mr, digits = 2)
```

## Test information functions

```{r tifs}
prob <- function(a, b, theta) {
  1 / (1 + exp(-1 * a * (theta - b)))
} 

information <- function(a, b, theta) {
  p <- prob(a, b, theta)
  q <- 1 - p
  a^2 * p * q
}

se_theta <- function(information) {
  1 / sqrt(information)
}

tif <- function(data, a_vec, b_vec, theta = seq(-5, 5, 0.01)) {
  info <- map2(data[[a_vec]], data[[b_vec]], ~information(.x, .y, theta)) %>% 
    pmap_dbl(sum)
  tibble(theta = theta,
         information = info,
         se = se_theta(information),
         rel = 1 - se^2,
         rel_range = ifelse(rel >= 0.8, "0.80", ifelse(
           rel >= 0.7 & rel < 0.8, "0.70", 
           NA_character_)
         )
  )
}

plot_information <- function(tif_df, grade, tier, content) {
  content <- ifelse(content == "ela", "ELA", stringr::str_to_title(content))
  
  ggplot(tif_df, aes(theta, information)) +
    geom_ribbon(aes(ymin = 0,
                    ymax = information,
                    fill = rel_range)) +
    geom_line() +
    scale_fill_manual(name = "Reliability Range",
                      breaks = c("0.70", "0.80"),
                      values = c("#b2cdf0", "#4f8dde")) +
    labs(x = "Theta",
         y = "Information",
         title = "Test Information Function",
         subtitle = glue::glue("{content}: Grade {grade} Tier {tier}"))
}
  
items_by_test <- items_by_test %>% 
  mutate(tif = map(data, ~tif(.x, "a_estimate", "b_estimate")),
         plot = pmap(list(tif, grade, tier, content), plot_information)) %>% 
  arrange(grade, tier, content)

walk(items_by_test$plot, print)
```