---
title: "ch4"
author: "BRT"
date: "8/19/2020"
output: 
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary of Validity Based on Content (Formerly Chapter 4)
A number of dimensions are considered in the content covered across AECs. First, the type of item is organized into (a) anchor items, that facilitate form comparability from year to year, (b) Linking Tier 1 items (LT1) for low performing students assigned to this Tier, (c) Linking Tier 2 (LT2) for higher performing students assigned to this Tier, and (d) unique items (d) that are being field tested for eventual placement on the test in future years. Note that the test for each Tier includes LT1 and LT2 so that students not placed in that Tier can perform not only on the items in their assigned Tier but also take items in the Tier where they are not placed. This cross walk of items with students is important linking the two Tiers with both populations.

**Summary of Alternate Eligible Content (AECs) by Item Code, Content Category, and Tier**  
In English Language Arts, four categories of content are included: Literature, Information, Writing, and language. In Mathematics, four content categories are included: numbers and operations, operations and algebra, geometry, and measurement and data. In Science, four categories of content are included: natural science, biology. Physics, and earth-space. In all grades, these items are one of four types (Anchor, LT1, LT2, and Unique) and used in either Tier 1 and/or Tier 2.

See [Appendix 1.7 (ELA)](appendix/App1.7_AEC_By_ItemCodeCntCatELA.pdf), [Appendix 1.8 (Math)](appendix/App1.8_AEC_By_ItemCodeCntCatMath.pdf), [Appendix 1.9 (Science)](appendix/App1.9_AEC_By_ItemCodeCntCatSci.pdf)

**Summary of Appendices/Findings.**  The PASA tests are systematically organized to reflect not only a broad range of Alternate Eligible Content (AECs) in English Language Arts (ELA), Mathematics, and Science) but also a number of content categories to appropriately distinguish these complex constructs. Furthermore, this range is considered across both tiers and four types of items (anchor [A], linking to Tier 1 [LT1], linking to Tier 2 [LT2], and unique [U]). Two problems, however, result in stretching the item bank across so many dimensions: (a) many cells have no or few items, and (b) distinguishing anchor-linking items was unfruitful as both a- and b-parameters were missing where they should have been (A, LT1, and LT2) and present where they should not have been present U). Therefore, to connect the scale to that used last year (2019), all items with a- and b-parameters were used irrespective of designation.

### Item Quality (IQ) Reports for ELA-Math and Science
In the fall of 2019, all items in all subject areas, grades, and tier were revised in the number of prompts allowed, from multiple (2+) prompts to only 1. At the same time, errors were corrected and the language of the prompts clarified and reduced in verbiage. Each item was reviewed and revised by personnel in Behavioral Research and Teaching (BRT), then reviewed by personnel from the Bureau of Special Education, and finally reviewed by teachers in PA. Using the Distributed Item Review (DIR) process, teachers were assigned by grade band and subject area to respond to a number of statements reflecting item-standards alignment and bias. Two reports were published that document the entire process and the item quality.

See [Appendix 1.10 (ELA and Mathematics)](appendix/App1.10_ItemQualityReport_ELAandMath.pdf)  and [Appendix 1.11 (Science)](appendix/App1.11_ItemQualityReport_Science.pdf)

**Summary of Appendices/Findings**  The reports reflect positive reactions from teachers across all subject areas, grades, and tiers. They generally approved of the (a) correctness of the items, (b) the use of a single prompt, and (c) the structure/format of the item in line with the presentation of the main stimulus and options. As expected, some variation existed among the teacher teams and individual judges.

### Identification of Standards with Common Items Across Tiers  – Pivot Tables with Item Map files
In the summer of 2020, researchers at Behavioral Research and Teaching (BRT) used item maps to fix the scale to be the same as used in 2019, allowing comparisons to be made over time. In the end, after discovering that all items were used with a-parameters and b-parameters (irrespective of their code A, LT1, LT2, or U). In this appendix, tables present the number of items used within content categories.

See [Appendix 1.12 (ELA, Mathematics, and Science)](appendix/App1.12_ItemParameterSummary.xlsx)

**Summary of Appendices/Findings.**  The content covered across tiers is sufficient in the number of items to allow the 2019 scale to be used.